version: '2'
services:
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myapp/src
      - ./screenshot:/myapp/screenshot
      - ./logs:/myapp/logs
    depends_on:
      - selenium-hub
      - chrome-swarm
      - firefox-swarm
    working_dir: /myapp
    command: /bin/bash -c "gulp test"

  selenium-hub:
    container_name: "selenium-hub"
    image: selenium/hub:3.5.0
    ports:
      - 4444:4444
    environment:
      GRID_TIMEOUT: 10000

  chrome-swarm:
    container_name: "chrome-swarm"
    image: selenium/node-chrome:3.5.0
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm

  firefox-swarm:
    container_name: "firefox-swarm"
    image: selenium/node-firefox:3.5.0
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm